/*
 * pa-data.js — read a game's puzzle data whether the page is served or opened
 * off a disk.
 *
 * Every hero game and the hub load their packs with fetch(). That is correct
 * on a web server and dead on arrival from a file:// page: a browser gives a
 * local file an opaque origin and blocks fetch outright, so double-clicking
 * index.html produced five games that all reported their pack missing. The
 * client preview is handed over as a folder, and there is no way to know
 * whether the person receiving it will put it on a host or open it from their
 * desktop — so it has to work both ways, from one build.
 *
 * A <script> tag is NOT blocked on file://. So the published tree ships each
 * data file as a JS sidecar next to it — `puzzles/index.json.js` holding
 *
 *     window.__PA_DATA["puzzles/index.json"] = { … };
 *
 * — and this module injects that sidecar instead of fetching. The key is the
 * exact string the calling code already passes, so no caller has to know
 * where it is running or what its own URL is.
 *
 * Order of attempts, and each fallback is real:
 *   1. already in __PA_DATA        — the sidecar has been loaded before
 *   2. inject the sidecar          — works on file: and on http alike
 *   3. fetch the original          — the repo during development, where no
 *                                    sidecars have been generated
 *
 * Sidecars are generated by publish-preview.mjs. Nothing here is specific to
 * that script: a game that has none simply falls through to fetch and behaves
 * exactly as it did before this file existed.
 */
(function () {
  'use strict';

  var DATA = (window.__PA_DATA = window.__PA_DATA || {});
  var pending = {};

  /* A sidecar that has already failed must not be retried on every puzzle the
     reader opens — thirty missing accept lists would otherwise mean thirty
     404s each time. */
  var dead = {};

  function inject(key) {
    if (pending[key]) return pending[key];
    pending[key] = new Promise(function (resolve, reject) {
      var s = document.createElement('script');
      s.src = key + '.js';
      s.async = true;
      s.onload = function () {
        /* Loaded, but the sidecar may not have registered the key it was
           named for — a truncated or mis-generated file. Treat that as a
           miss rather than as data. */
        if (Object.prototype.hasOwnProperty.call(DATA, key)) resolve(DATA[key]);
        else reject(new Error('sidecar loaded but registered nothing for ' + key));
        if (s.parentNode) s.parentNode.removeChild(s);
      };
      s.onerror = function () {
        if (s.parentNode) s.parentNode.removeChild(s);
        reject(new Error('no sidecar for ' + key));
      };
      (document.head || document.documentElement).appendChild(s);
    });
    return pending[key];
  }

  /* `kind` is 'json' or 'text'. A sidecar always registers the parsed value
     for json and the raw string for text, so the two paths return the same
     shape whichever route the data arrived by. */
  function load(key, kind) {
    if (Object.prototype.hasOwnProperty.call(DATA, key)) return Promise.resolve(DATA[key]);

    var viaFetch = function () {
      return fetch(key).then(function (r) {
        if (!r.ok) throw new Error(r.status + ' for ' + key);
        return kind === 'text' ? r.text() : r.json();
      });
    };

    if (dead[key]) return viaFetch();

    return inject(key).catch(function () {
      dead[key] = true;
      return viaFetch();
    });
  }

  window.PaData = {
    json: function (key) { return load(key, 'json'); },
    text: function (key) { return load(key, 'text'); },
    /* True when the page is running off a disk, which is the case the
       sidecars exist for. Exposed so a surface can say something useful if
       even the sidecar route fails. */
    isLocal: function () { return location.protocol === 'file:'; }
  };
}());
