/* Generated by publish-preview.mjs — lets this game load without a web
   server. See shared/pa-data.js. */
(function (d) { var v = {
  "game": "crossword-bn",
  "title": "শব্দভেদ",
  "note": "Archive. The daily is the puzzle whose date is today, falling back to the most recent one already published; a future-dated puzzle is never served. Everything listed here is browsable in-game, so only validated transcriptions belong — run `node puzzles/validate.mjs` before adding one.",
  "puzzles": [
    { "id": "pa-2026-08-05", "date": "2026-08-05" },
    { "id": "pa-2026-08-06", "date": "2026-08-06" },
    { "id": "pa-2026-08-07", "date": "2026-08-07" },
    { "id": "pa-2026-08-08", "date": "2026-08-08" },
    { "id": "pa-2026-08-09", "date": "2026-08-09" }
  ]
};
  d["puzzles/index.json"] = v;
  d["../games/crossword-bn/puzzles/index.json"] = v;
}(window.__PA_DATA = window.__PA_DATA || {}));
