/* Generated by publish-preview.mjs — lets this game load without a web
   server. See shared/pa-data.js. */
(function (d) { var v = {
  "id": "pa-2026-08-11",
  "date": "2026-08-11",
  "source": "Prothom Alo print edition, শব্দভেদ, 2026-08-11. Grid and clues from Screenshot/11.8.2026.png; solution grid from Screenshot/12.8.2026.png.",
  "verified": true,
  "verificationNote": "Block pattern derived from ink in the printed solution grid rather than from the tint; all 12 across and 10 down clues resolve against the grid; numbering, interlock and akshara-per-cell confirmed by puzzles/validate.mjs.",
  "rows": 8,
  "cols": 8,
  "grid": [
    "ম",
    null,
    "অ",
    null,
    "অ",
    "সু",
    "খ",
    null,
    "হা",
    "স্য",
    "ক",
    "র",
    null,
    "গ",
    null,
    "গ",
    "ফে",
    null,
    "থ্য",
    null,
    "কা",
    "ঠ",
    "খ",
    "ড়",
    "জ",
    "য়",
    null,
    "ম",
    "ন",
    "ন",
    null,
    "ব",
    "খা",
    null,
    "মা",
    null,
    "কো",
    null,
    "হা",
    "ড়",
    "না",
    "গ",
    "রি",
    "ক",
    null,
    "কা",
    "ত",
    null,
    null,
    "র",
    null,
    "থা",
    "মা",
    null,
    "য",
    "ত্ন",
    "অ",
    "ল",
    "স",
    null,
    "না",
    "লি",
    "শ",
    null
  ],
  "entries": [
    {
      "n": 1,
      "dir": "down",
      "cell": 0,
      "len": 6,
      "clue": "দলিলপত্র সংরক্ষণ করে রাখার ঘর।"
    },
    {
      "n": 2,
      "dir": "down",
      "cell": 2,
      "len": 3,
      "clue": "বলার অযোগ্য।"
    },
    {
      "n": 3,
      "dir": "across",
      "cell": 4,
      "len": 3,
      "clue": "ব্যাধি।"
    },
    {
      "n": 4,
      "dir": "down",
      "cell": 5,
      "len": 4,
      "clue": "সুন্দর গড়ন।"
    },
    {
      "n": 5,
      "dir": "across",
      "cell": 8,
      "len": 4,
      "clue": "হাসি উদ্রেককারী।"
    },
    {
      "n": 6,
      "dir": "down",
      "cell": 15,
      "len": 4,
      "clue": "বিশৃঙ্খলা, অনিয়ম।"
    },
    {
      "n": 7,
      "dir": "across",
      "cell": 20,
      "len": 4,
      "clue": "কাঠ ও শুকনা তৃণ।"
    },
    {
      "n": 7,
      "dir": "down",
      "cell": 20,
      "len": 3,
      "clue": "মাছের ফুলকার ওপরের শক্ত আবরণ।"
    },
    {
      "n": 8,
      "dir": "across",
      "cell": 24,
      "len": 2,
      "clue": "যুদ্ধ ইত্যাদির মাধ্যমে অধিকার করা।"
    },
    {
      "n": 9,
      "dir": "across",
      "cell": 27,
      "len": 3,
      "clue": "অনবরত অনুচিন্তন।"
    },
    {
      "n": 10,
      "dir": "down",
      "cell": 34,
      "len": 2,
      "clue": "মড়ক।"
    },
    {
      "n": 11,
      "dir": "across",
      "cell": 38,
      "len": 2,
      "clue": "অস্থি।"
    },
    {
      "n": 11,
      "dir": "down",
      "cell": 38,
      "len": 4,
      "clue": "দক্ষতার খ্যাতি।"
    },
    {
      "n": 12,
      "dir": "across",
      "cell": 40,
      "len": 4,
      "clue": "নগরের অধিবাসী।"
    },
    {
      "n": 13,
      "dir": "down",
      "cell": 41,
      "len": 3,
      "clue": "বিষ।"
    },
    {
      "n": 14,
      "dir": "down",
      "cell": 43,
      "len": 2,
      "clue": "উক্তি।"
    },
    {
      "n": 15,
      "dir": "across",
      "cell": 45,
      "len": 2,
      "clue": "পাশ, দিক।"
    },
    {
      "n": 16,
      "dir": "across",
      "cell": 51,
      "len": 2,
      "clue": "থেমে যাওয়া।"
    },
    {
      "n": 17,
      "dir": "down",
      "cell": 52,
      "len": 2,
      "clue": "নিষেধ।"
    },
    {
      "n": 18,
      "dir": "across",
      "cell": 54,
      "len": 2,
      "clue": "সেবা, খাতির।"
    },
    {
      "n": 19,
      "dir": "across",
      "cell": 56,
      "len": 3,
      "clue": "কুঁড়ে।"
    },
    {
      "n": 20,
      "dir": "across",
      "cell": 60,
      "len": 3,
      "clue": "অভিযোগ।"
    }
  ]
};
  d["puzzles/pa-2026-08-11.json"] = v;
  d["../games/crossword-bn/puzzles/pa-2026-08-11.json"] = v;
}(window.__PA_DATA = window.__PA_DATA || {}));
