/* Generated by publish-preview.mjs — lets this game load without a web
   server. See shared/pa-data.js. */
(function (d) { var v = {
  "id": "pa-2026-08-17",
  "date": "2026-08-17",
  "source": "Prothom Alo print edition, শব্দভেদ, 2026-08-17. Grid and clues from Screenshot/17.8.2026.png; solution grid from Screenshot/18.8.2026.png.",
  "verified": true,
  "verificationNote": "Block pattern derived from ink in the printed solution grid rather than from the tint; all 10 across and 8 down clues resolve against the grid; numbering, interlock and akshara-per-cell confirmed by puzzles/validate.mjs.",
  "rows": 8,
  "cols": 8,
  "grid": [
    "অ",
    "প",
    "রা",
    "ধ",
    null,
    "ম",
    null,
    "হাঁ",
    null,
    "রি",
    null,
    "রা",
    "সা",
    "য়",
    "নি",
    "ক",
    "আ",
    "পা",
    "ত",
    "ত",
    null,
    "দা",
    null,
    "ডা",
    null,
    "ক",
    null,
    "ল",
    "তা",
    null,
    "ব",
    "ক",
    "ক",
    null,
    "স",
    null,
    "রা",
    "গা",
    "ন্ধ",
    null,
    "পা",
    "দ",
    "প্র",
    "দী",
    "প",
    null,
    "ক",
    "লা",
    "ল",
    null,
    "তি",
    null,
    "থ",
    null,
    "দা",
    null,
    null,
    "শো",
    "ভ",
    "ন",
    null,
    "কা",
    "তা",
    "র"
  ],
  "entries": [
    {
      "n": 1,
      "dir": "across",
      "cell": 0,
      "len": 4,
      "clue": "গর্হিত কাজ, দোষ।"
    },
    {
      "n": 2,
      "dir": "down",
      "cell": 1,
      "len": 4,
      "clue": "হজম।"
    },
    {
      "n": 3,
      "dir": "down",
      "cell": 3,
      "len": 4,
      "clue": "পৃথিবীর উপরিভাগ।"
    },
    {
      "n": 4,
      "dir": "down",
      "cell": 5,
      "len": 3,
      "clue": "পরিষ্কৃত গমের মিহি গুঁড়া।"
    },
    {
      "n": 5,
      "dir": "down",
      "cell": 7,
      "len": 4,
      "clue": "উচ্চ স্বরে ডাকাডাকি।"
    },
    {
      "n": 6,
      "dir": "across",
      "cell": 11,
      "len": 5,
      "clue": "রসায়নবিষয়ক।"
    },
    {
      "n": 7,
      "dir": "across",
      "cell": 16,
      "len": 4,
      "clue": "এখনকার মতো।"
    },
    {
      "n": 8,
      "dir": "across",
      "cell": 27,
      "len": 2,
      "clue": "বল্লরি।"
    },
    {
      "n": 9,
      "dir": "down",
      "cell": 28,
      "len": 4,
      "clue": "আকাশ বা গগন।"
    },
    {
      "n": 10,
      "dir": "across",
      "cell": 30,
      "len": 2,
      "clue": "মাছ শিকারে পটু সাদা পাখি।"
    },
    {
      "n": 10,
      "dir": "down",
      "cell": 30,
      "len": 5,
      "clue": "যে ব্যক্তি নিজের সম্পত্তি বন্ধক রাখে।"
    },
    {
      "n": 11,
      "dir": "down",
      "cell": 32,
      "len": 3,
      "clue": "ললাট।"
    },
    {
      "n": 12,
      "dir": "down",
      "cell": 34,
      "len": 4,
      "clue": "বুদ্ধিমান, চটপটে।"
    },
    {
      "n": 13,
      "dir": "across",
      "cell": 36,
      "len": 3,
      "clue": "রাগে জ্ঞানশূন্য।"
    },
    {
      "n": 14,
      "dir": "across",
      "cell": 40,
      "len": 5,
      "clue": "রঙ্গমঞ্চে অভিনেতার পায়ের কাছে যে আলো স্থাপন করা হয়।"
    },
    {
      "n": 15,
      "dir": "across",
      "cell": 46,
      "len": 2,
      "clue": "কদলী।"
    },
    {
      "n": 16,
      "dir": "across",
      "cell": 57,
      "len": 3,
      "clue": "শোভাযুক্ত।"
    },
    {
      "n": 17,
      "dir": "across",
      "cell": 61,
      "len": 3,
      "clue": "শ্রেণি, পঙ্‌ক্তি।"
    }
  ]
};
  d["puzzles/pa-2026-08-17.json"] = v;
  d["../games/crossword-bn/puzzles/pa-2026-08-17.json"] = v;
}(window.__PA_DATA = window.__PA_DATA || {}));
