/* Generated by publish-preview.mjs — lets this game load without a web
   server. See shared/pa-data.js. */
(function (d) { var v = {
  "id": "pa-2026-08-06",
  "date": "2026-08-06",
  "source": "Prothom Alo print edition, শব্দভেদ, 6 August 2026. Grid and clues from Screenshot/6.8.26.png; solution grid from Screenshot/7.8.26.png.",
  "verified": true,
  "verificationNote": "All 12 across and 13 down clues resolve against the grid; numbering, interlock and akshara-per-cell confirmed by puzzles/validate.mjs.",
  "rows": 8,
  "cols": 8,
  "grid": [
    null, "কা", null, "বে", "গ", null, "নী", null,
    "অ", "র", "ক্ষি", "ত", null, "ব", "র", "ফ",
    null, "সা", null, "ন", "গ", "দ", null, "স",
    "হা", "জি", "র", null, "ঞ্জ", null, "কো", "ল",
    "র", null, "ফা", "ল", null, "মা", "টি", null,
    null, "অ", null, "ট", "গ", "র", null, "বা",
    "হ", "ত", "বা", "ক", null, "ধ", "ম", "ক",
    null, "ল", null, "ন", "খ", "র", null, "ল"
  ],
  "entries": [
    { "n": 2,  "dir": "across", "cell": 3,  "len": 2, "clue": "দ্রুতগতি।" },
    { "n": 4,  "dir": "across", "cell": 8,  "len": 4, "clue": "সুরক্ষিত নয় এমন।" },
    { "n": 5,  "dir": "across", "cell": 13, "len": 3, "clue": "ঠান্ডায় জমাটবাঁধা পানি।" },
    { "n": 7,  "dir": "across", "cell": 19, "len": 3, "clue": "বাকির বিপরীত।" },
    { "n": 9,  "dir": "across", "cell": 24, "len": 3, "clue": "উপস্থিত।" },
    { "n": 11, "dir": "across", "cell": 30, "len": 2, "clue": "ক্রোড়।" },
    { "n": 12, "dir": "across", "cell": 34, "len": 2, "clue": "লাঙলের ফলা।" },
    { "n": 14, "dir": "across", "cell": 37, "len": 2, "clue": "মৃত্তিকা।" },
    { "n": 16, "dir": "across", "cell": 43, "len": 3, "clue": "একধরনের সুন্দর সাদা ফুল।" },
    { "n": 18, "dir": "across", "cell": 48, "len": 4, "clue": "অবাক, বিস্মিত।" },
    { "n": 19, "dir": "across", "cell": 53, "len": 3, "clue": "বকুনি।" },
    { "n": 20, "dir": "across", "cell": 59, "len": 3, "clue": "পশুপাখির তীক্ষ্ণধার নখ।" },

    { "n": 1,  "dir": "down", "cell": 1,  "len": 4, "clue": "কূটকৌশল।" },
    { "n": 2,  "dir": "down", "cell": 3,  "len": 3, "clue": "মাহিনা।" },
    { "n": 3,  "dir": "down", "cell": 6,  "len": 2, "clue": "পানি।" },
    { "n": 5,  "dir": "down", "cell": 13, "len": 2, "clue": "মন্দ।" },
    { "n": 6,  "dir": "down", "cell": 15, "len": 3, "clue": "খেতে উৎপন্ন শস্য।" },
    { "n": 8,  "dir": "down", "cell": 20, "len": 2, "clue": "শস্য কেনাবেচার স্থান।" },
    { "n": 9,  "dir": "down", "cell": 24, "len": 2, "clue": "পরাজয়।" },
    { "n": 10, "dir": "down", "cell": 26, "len": 2, "clue": "মীমাংসা।" },
    { "n": 11, "dir": "down", "cell": 30, "len": 2, "clue": "ক্রোড়।" },
    { "n": 13, "dir": "down", "cell": 35, "len": 4, "clue": "লালাভ সবুজ ফলযুক্ত গাছ।" },
    { "n": 14, "dir": "down", "cell": 37, "len": 4, "clue": "প্রহার করা।" },
    { "n": 15, "dir": "down", "cell": 41, "len": 3, "clue": "তল নেই এমন।" },
    { "n": 17, "dir": "down", "cell": 47, "len": 3, "clue": "গাছের ছাল।" }
  ]
};
  d["puzzles/pa-2026-08-06.json"] = v;
  d["../games/crossword-bn/puzzles/pa-2026-08-06.json"] = v;
}(window.__PA_DATA = window.__PA_DATA || {}));
