/* Generated by publish-preview.mjs — lets this game load without a web
   server. See shared/pa-data.js. */
(function (d) { var v = {
  "id": "pa-2026-08-09",
  "date": "2026-08-09",
  "source": "Prothom Alo print edition, শব্দভেদ, 9 August 2026. Grid and clues from Screenshot/9.8.26.png; solution grid from Screenshot/10.8.26.png.",
  "verified": true,
  "verificationNote": "All 15 across and 14 down clues resolve against the grid; numbering, interlock and akshara-per-cell confirmed by puzzles/validate.mjs. 8-across (ধাপ্পা) and 13-across (ভস্ত্রা) were re-read against the scan on a second pass and confirmed verbatim — an earlier pass had misread them as ধাক্কা and ভস্ম, which do not match their answers.",
  "rows": 8,
  "cols": 8,
  "grid": [
    "খ", "ড়", "খ", "ড়ি", null, "ঘ", "ট", "না",
    "ল", null, "ট", null, "বো", "ন", null, "ট্য",
    null, "আঁ", "কা", "বাঁ", "কা", null, "ধোঁ", "কা",
    "কা", "চ", null, "শ", null, "হাঁ", null, "র",
    "গ", "ড়", "ন", null, "হা", "প", "র", null,
    "জ", null, "মু", "গ্ধ", "তা", null, "সা", "রি",
    null, "দে", "না", null, "হা", "ম", null, "ক্ত",
    "ত", "রি", null, "বা", "তি", null, "হা", "তা"
  ],
  "entries": [
    { "n": 1,  "dir": "across", "cell": 0,  "len": 4, "clue": "দরজা-জানালার ফাঁকযুক্ত কপাট।" },
    { "n": 3,  "dir": "across", "cell": 5,  "len": 3, "clue": "ব্যাপার, যা ঘটে।" },
    { "n": 5,  "dir": "across", "cell": 12, "len": 2, "clue": "ভগিনী।" },
    { "n": 6,  "dir": "across", "cell": 17, "len": 4, "clue": "বহু স্থানে বাঁকা।" },
    { "n": 8,  "dir": "across", "cell": 22, "len": 2, "clue": "ধাপ্পা।" },
    { "n": 9,  "dir": "across", "cell": 24, "len": 2, "clue": "বালু ও ক্ষার থেকে তৈরি ভঙ্গুর বস্তু।" },
    { "n": 11, "dir": "across", "cell": 32, "len": 3, "clue": "আকার, চেহারা।" },
    { "n": 13, "dir": "across", "cell": 36, "len": 3, "clue": "ভস্ত্রা।" },
    { "n": 15, "dir": "across", "cell": 42, "len": 3, "clue": "মোহগ্রস্ততা।" },
    { "n": 16, "dir": "across", "cell": 46, "len": 2, "clue": "পঙ্‌ক্তি, শ্রেণি।" },
    { "n": 18, "dir": "across", "cell": 49, "len": 2, "clue": "কর্জ।" },
    { "n": 19, "dir": "across", "cell": 52, "len": 2, "clue": "গুটিকাযুক্ত সংক্রামক জ্বর।" },
    { "n": 20, "dir": "across", "cell": 56, "len": 2, "clue": "নৌকা।" },
    { "n": 21, "dir": "across", "cell": 59, "len": 2, "clue": "প্রদীপ।" },
    { "n": 22, "dir": "across", "cell": 62, "len": 2, "clue": "জামার আস্তিন।" },

    { "n": 1,  "dir": "down", "cell": 0,  "len": 2, "clue": "ক্রূর।" },
    { "n": 2,  "dir": "down", "cell": 2,  "len": 3, "clue": "সন্দেহ, সংশয়।" },
    { "n": 3,  "dir": "down", "cell": 5,  "len": 2, "clue": "নিবিড়।" },
    { "n": 4,  "dir": "down", "cell": 7,  "len": 4, "clue": "নাটক লেখক।" },
    { "n": 5,  "dir": "down", "cell": 12, "len": 2, "clue": "যার বুদ্ধি বা কাণ্ডজ্ঞান কম।" },
    { "n": 6,  "dir": "down", "cell": 17, "len": 3, "clue": "নখের আঘাত।" },
    { "n": 7,  "dir": "down", "cell": 19, "len": 2, "clue": "বংশ, বেণু।" },
    { "n": 9,  "dir": "down", "cell": 24, "len": 3, "clue": "লেখা, আঁকা বা মুদ্রণের উপকরণ।" },
    { "n": 10, "dir": "down", "cell": 29, "len": 2, "clue": "দম।" },
    { "n": 12, "dir": "down", "cell": 34, "len": 3, "clue": "নিদর্শন।" },
    { "n": 13, "dir": "down", "cell": 36, "len": 4, "clue": "হাত দিয়ে পরস্পর মারামারি।" },
    { "n": 14, "dir": "down", "cell": 38, "len": 2, "clue": "রসযুক্ত।" },
    { "n": 17, "dir": "down", "cell": 47, "len": 3, "clue": "শূন্যতা।" },
    { "n": 18, "dir": "down", "cell": 49, "len": 2, "clue": "বিলম্ব।" }
  ]
};
  d["puzzles/pa-2026-08-09.json"] = v;
  d["../games/crossword-bn/puzzles/pa-2026-08-09.json"] = v;
}(window.__PA_DATA = window.__PA_DATA || {}));
